#!/bin/sh

set -e

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

echo "debug output: disk usage on $(hostname) at $(date -u)"
df -h
echo

# exit if we are in the same UTS namespace as init ( != 2nd build )
[ "$(readlink /proc/1/ns/uts)" = "$(readlink /proc/self/ns/uts)" ] && exit 0

# cease using disorderfs
if [ -d /tmp/disorderfs ] ; then
	echo -n "Unmounting /tmp/disorderfs…"
	fusermount -z -u "$BUILDDIR"
	rmdir "$BUILDDIR"
	mv /tmp/disorderfs "$BUILDDIR"
	echo " done."
fi
