#!/bin/sh

set -e

# exit if we are in the same UTS namespace as init ( != 2nd build )
[ "$(readlink /proc/1/ns/uts)" = "$(readlink /proc/self/ns/uts)" ] && exit 0

# cease using disorderfs
fusermount -u /tmp/buildd
mv /tmp/disorderfs /tmp/buildd
