#!/bin/sh

set -e

# exit if we are in the same UTS namespace as init ( != 2nd build )
[ "$(readlink /proc/1/ns/uts)" = "$(readlink /proc/self/ns/uts)" ] && exit 0

echo "I: Changing host+domainname to test build reproducibility" >&2
sed -e '/^127.0.0.1/s/$/ i-capture-the-hostname i-capture-the-hostname.i-capture-the-domain/' -i /etc/hosts
hostname i-capture-the-hostname
domainname i-capture-the-domain
echo "I: Adding a custom variable just for the fun of it..." >&2
export CAPTURE_ENVIRONMENT="I capture the environment"

# use disorderfs, mount it as user
if [ -x /usr/bin/disorderfs ] ; then
	mknod -m 666 /dev/fuse c 10 229
	mv /tmp/buildd /tmp/disorderfs
	mkdir /tmp/buildd
	su pbuilder2 -c 'disorderfs /tmp/disorderfs /tmp/buildd'
else
	echo "Warning: disorderfs not available."
fi
