#!/bin/sh

# maybe I'm too stupid to use apaches REMOTE_HOST directive correctly
# I couldn't get it to work. so I use REMOTE_ADDR...
# see etc/apache2/sites-available/jenkins.debian.net

if [ "$(host git.debian.org)" != "git.debian.org has address 217.196.43.140" ] ; then
	echo "IP address of git.debian.org has changed, please update etc/apache2/sites-available/jenkins.debian.net and etc/cron.daily/jenkins"
fi
