#!/bin/sh

# Copyright 2012 Holger Levsen <holger@layer-acht.org>
# released under the GPLv=2

[ -x /usr/bin/visitors ] || exit 0
[ -x /usr/bin/ip2host ] || exit 0

if [ ! -f /usr/share/doc/zutils/copyright ] ; then
	echo package zutils needs to be installed too
	exit 1
fi

LOGS=$(mktemp)
DOT=$(mktemp)
# FIXME: provide monthly stats and don't run this daily
zcat /var/log/apache2/access.log* | grep -v 127.0.0.1 | sort | ip2host > $LOGS

visitors --debug -AKMY -m 30 $LOGS > /var/www/visitors-report.html 2> /dev/null
#visitors --debug -VT -m 30 --prefix https://jenkins.debian.net $LOGS > $DOT
# dot -Tpng -o/var/lib/www/visitors-report-graph.png $DOT

rm $LOGS $DOT
