#!/bin/sh

# Copyright 2012 Holger Levsen <holger@layer-acht.org>
# released under the GPLv=2

LOGS=$(mktemp)
DOT=$(mktemp)
# FIXME: provide monthly stats and don't run this daily
zcat /var/log/apache2/access.log* | grep -v 127.0.0.1 | sort | ip2host > $LOGS

visitors --debug -AKMY -m 30 $LOGS > /var/www/visitors-report.html
#visitors --debug -VT -m 30 --prefix http://jenkins.debian.net $LOGS > $DOT
# dot -Tpng -o/var/lib/www/visitors-report-graph.png $DOT

rm $LOGS $DOT
