#!/bin/bash

set -e

# exit if we are in the same UTS namespace as init ( != 2nd build )
[ "$(readlink /proc/1/ns/uts)" = "$(readlink /proc/self/ns/uts)" ] && exit 0

cd $BUILDDIR

if [ "$(basename $(pwd))" != "2nd" ]; then
	# build path variation disabled, so do nothing
	exit 0
fi

# There should be only one file, the source directory.
src_dir=$(ls | head -n 1)

# We want to keep the build path length to minimise the diff. So we just
# replace the first char of the source dir.
mv $src_dir _${src_dir:1}
