#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

jenkins_reproducible_builds - Plugin to measure number of reproducible builds running

=head1 AUTHOR

Contributed by Holger Levsen

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

JOB_PREFIXES="first second"
if [ "$1" = "config" ]; then
	echo 'graph_title Concurrent reproducible builds running'
	echo 'graph_args --base 1000 -l 0 '
	echo 'graph_scale no'
	echo 'graph_total total'
	echo 'graph_vlabel Concurrent reproducible builds running'
	echo 'graph_category jenkins'
	draw=AREA
	for PREFIX in $JOB_PREFIXES ; do
		echo "jenkins_reproducible_${PREFIX}_build.label $PREFIX build"
		echo "jenkins_reproducible_${PREFIX}_build.draw $draw"
		if [ "$draw" = "AREA" ] ; then draw=STACK ; fi
	done
	exit 0
fi

for PREFIX in $JOB_PREFIXES ; do
	if [ "$PREFIX" = "first" ] ; then
		NR=$(pgrep -fc "bin/bash /srv/jenkins/bin/reproducible_build.sh 1")
	else
		NR=$(pgrep -fc "bin/bash /srv/jenkins/bin/reproducible_build.sh 2")
	fi
	echo "jenkins_reproducible_${PREFIX}_build.value $NR"
	done
