#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

jenkins_builds_running - Plugin to measure number of jenkins builds which are currently running

=head1 AUTHOR

Contributed by Holger Levsen

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

JOB_PREFIXES=$(ls -1 /var/lib/jenkins/jobs/|cut -d "-" -f1|sort -u)
if [ "$1" = "config" ]; then

        echo 'graph_title Jenkins Builds running'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel Jenkins Builds currently running'
        echo 'graph_category jenkins'
        echo "jenkins_builds_running.label $PREFIX builds_running"
        echo "jenkins_builds_running.draw AREA"
        exit 0
fi

echo "jenkins_builds_running.value $(ps fax|grep /tmp/hudson|grep -v grep|wc -l)"
